### ISSUE TITLE
Integrate metrics via Prometheus

### ISSUE THREAD

**Issue by alexellis** [hyperhq/faas-hyper#2]
Suggested `docker-compose.yml` config to get this working is below:

```
version: '2'
services:
  faas-hyper:
    image: imeoer/faas-hyper
    hostname: faas-hyper
    environment:
      - HYPER_ACCESS_KEY=key
      - HYPER_SECRET_KEY=secret
    ports:
      - 8080:8080
    restart: always

  prometheus:
    hostname: prometheus
    image: alexellis2/prometheus-hyper
    command: "-config.file=/etc/prometheus/prometheus.yml -storage.local.path=/prometheus -storage.local.memory-chunks=10000"
    ports:
      - 9090:9090

  gateway:
    image: functions/gateway:collated_stats_pr
    hostname: gateway
    environment:
      - functions_provider_url=http://faas-hyper:8080/
      - faas_prometheus_host=prometheus
    depends_on:
      - faas-hyper
      - prometheus
    ports:
      - 8080:8080
    fip: fip_ip
    restart: always
```
